"""Curated catalog of free, high-quality learning resources (YouTube courses)."""

from typing import Dict, List

RECOMMENDATION_CATALOG: Dict[str, Dict[str, str]] = {
    "Docker": {
        "title": "Docker Tutorial for Beginners (Full Course)",
        "platform": "YouTube",
        "creator": "TechWorld with Nana",
        "url": "https://www.youtube.com/watch?v=3c-iBn73dDE",
        "duration": "2.5 hours",
        "level": "Beginner to Intermediate",
    },
    "Kubernetes": {
        "title": "Kubernetes Tutorial for Beginners [Complete 4-Hour Course]",
        "platform": "YouTube",
        "creator": "TechWorld with Nana",
        "url": "https://www.youtube.com/watch?v=X48VuDVv0do",
        "duration": "3.5 hours",
        "level": "Intermediate",
    },
    "AWS": {
        "title": "AWS Certified Cloud Practitioner Training 2024",
        "platform": "YouTube",
        "creator": "freeCodeCamp.org",
        "url": "https://www.youtube.com/watch?v=SOTamWNgDKc",
        "duration": "4 hours",
        "level": "Beginner",
    },
    "Google Cloud": {
        "title": "Google Cloud Platform Full Course - 10 Hours",
        "platform": "YouTube",
        "creator": "freeCodeCamp.org",
        "url": "https://www.youtube.com/watch?v=4D3X63U7468",
        "duration": "10 hours",
        "level": "Beginner to Intermediate",
    },
    "Microsoft Azure": {
        "title": "Microsoft Azure Fundamentals (AZ-900) Full Course",
        "platform": "YouTube",
        "creator": "freeCodeCamp.org",
        "url": "https://www.youtube.com/watch?v=NKEFWyqJ5XA",
        "duration": "3 hours",
        "level": "Beginner",
    },
    "Redis": {
        "title": "Redis Crash Course - In-Memory Database & Caching",
        "platform": "YouTube",
        "creator": "Traversy Media",
        "url": "https://www.youtube.com/watch?v=jgpVdJB2sKQ",
        "duration": "1 hour",
        "level": "Beginner",
    },
    "PostgreSQL": {
        "title": "PostgreSQL Full Course for Beginners",
        "platform": "YouTube",
        "creator": "freeCodeCamp.org",
        "url": "https://www.youtube.com/watch?v=qw--VYLpxG4",
        "duration": "4 hours",
        "level": "Beginner",
    },
    "MongoDB": {
        "title": "MongoDB Complete Course - From Beginner to Advanced",
        "platform": "YouTube",
        "creator": "freeCodeCamp.org",
        "url": "https://www.youtube.com/watch?v=c2M-rlkkT5o",
        "duration": "2.5 hours",
        "level": "Beginner",
    },
    "GraphQL": {
        "title": "GraphQL Full Course - Beginner to Advanced",
        "platform": "YouTube",
        "creator": "freeCodeCamp.org",
        "url": "https://www.youtube.com/watch?v=ed8SzALpx1Q",
        "duration": "2 hours",
        "level": "Intermediate",
    },
    "React": {
        "title": "React 18 Full Course - Learn React in 2024",
        "platform": "YouTube",
        "creator": "freeCodeCamp.org",
        "url": "https://www.youtube.com/watch?v=bMknfKXIFA8",
        "duration": "12 hours",
        "level": "Beginner to Advanced",
    },
    "Next.js": {
        "title": "Next.js 14 Full Course - App Router, Server Actions",
        "platform": "YouTube",
        "creator": "Traversy Media",
        "url": "https://www.youtube.com/watch?v=wm5gMKuwSYk",
        "duration": "2 hours",
        "level": "Intermediate",
    },
    "TypeScript": {
        "title": "TypeScript Course for Beginners - 2024",
        "platform": "YouTube",
        "creator": "Academind / freeCodeCamp.org",
        "url": "https://www.youtube.com/watch?v=BwuLxPH8IDs",
        "duration": "3 hours",
        "level": "Beginner to Intermediate",
    },
    "Python": {
        "title": "Python for Beginners - Full Course",
        "platform": "YouTube",
        "creator": "freeCodeCamp.org",
        "url": "https://www.youtube.com/watch?v=rfscVS0vtbw",
        "duration": "4.5 hours",
        "level": "Beginner",
    },
    "FastAPI": {
        "title": "FastAPI - A Python Framework for High Performance APIs",
        "platform": "YouTube",
        "creator": "freeCodeCamp.org",
        "url": "https://www.youtube.com/watch?v=tLKKmouUAMS",
        "duration": "4 hours",
        "level": "Intermediate",
    },
    "CI/CD": {
        "title": "CI/CD Pipeline with GitHub Actions - Complete Course",
        "platform": "YouTube",
        "creator": "TechWorld with Nana",
        "url": "https://www.youtube.com/watch?v=R8_veQiYBjI",
        "duration": "2 hours",
        "level": "Intermediate",
    },
    "Terraform": {
        "title": "Terraform Course - Automate Your AWS Infrastructure",
        "platform": "YouTube",
        "creator": "freeCodeCamp.org",
        "url": "https://www.youtube.com/watch?v=SLB_c_ayRMo",
        "duration": "2.5 hours",
        "level": "Intermediate",
    },
    "Data Structures and Algorithms": {
        "title": "Algorithms and Data Structures Tutorial",
        "platform": "YouTube",
        "creator": "freeCodeCamp.org",
        "url": "https://www.youtube.com/watch?v=8hly31xKli0",
        "duration": "5 hours",
        "level": "Beginner to Advanced",
    },
    "System Design": {
        "title": "System Design Course for Beginners",
        "platform": "YouTube",
        "creator": "freeCodeCamp.org",
        "url": "https://www.youtube.com/watch?v=m8Icp_Cid5o",
        "duration": "2.5 hours",
        "level": "Intermediate to Advanced",
    },
    "Machine Learning": {
        "title": "Machine Learning for Everybody - Full Course",
        "platform": "YouTube",
        "creator": "freeCodeCamp.org",
        "url": "https://www.youtube.com/watch?v=i_LwzRVP7bg",
        "duration": "4 hours",
        "level": "Beginner",
    },
    "PyTorch": {
        "title": "PyTorch for Deep Learning Bootcamp",
        "platform": "YouTube",
        "creator": "freeCodeCamp.org",
        "url": "https://www.youtube.com/watch?v=V_xro1bcAuA",
        "duration": "26 hours",
        "level": "Beginner to Advanced",
    },
    "Tailwind CSS": {
        "title": "Tailwind CSS Full Course for Beginners",
        "platform": "YouTube",
        "creator": "Dave Gray",
        "url": "https://www.youtube.com/watch?v=lCxcTsOHrjo",
        "duration": "3 hours",
        "level": "Beginner",
    },
    "Git": {
        "title": "Git and GitHub for Beginners - Crash Course",
        "platform": "YouTube",
        "creator": "freeCodeCamp.org",
        "url": "https://www.youtube.com/watch?v=RGOj5yH7evk",
        "duration": "1 hour",
        "level": "Beginner",
    },
    "Node.js": {
        "title": "Node.js and Express.js - Full Course",
        "platform": "YouTube",
        "creator": "freeCodeCamp.org",
        "url": "https://www.youtube.com/watch?v=Oe421EPjeBE",
        "duration": "8 hours",
        "level": "Beginner to Intermediate",
    },
    "Java": {
        "title": "Java Tutorial for Beginners [Full Course]",
        "platform": "YouTube",
        "creator": "Programming with Mosh",
        "url": "https://www.youtube.com/watch?v=eIrMbAQSU34",
        "duration": "2.5 hours",
        "level": "Beginner",
    },
    "Spring Boot": {
        "title": "Spring Boot Tutorial for Beginners",
        "platform": "YouTube",
        "creator": "Amigoscode",
        "url": "https://www.youtube.com/watch?v=9SGDpanrc8U",
        "duration": "3 hours",
        "level": "Intermediate",
    },
}
